version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - APP_NAME=glossika-exercise
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
      - MYSQL_USER=glossika
      - MYSQL_PASSWORD=1qaz2wsx
      - MYSQL_DATABASE=glossika
  redis:
    container_name: redis
    image: redis:7.0.10
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: [ redis-server, /usr/local/etc/redis/redis.conf ]